// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxhyr556e5rXAgtvJPZRibq0sNrLqdE40',
    appId: '1:648139194030:web:bce2e2ed920f1a03ee773f',
    messagingSenderId: '648139194030',
    projectId: 'project-matkul',
    authDomain: 'project-matkul.firebaseapp.com',
    storageBucket: 'project-matkul.appspot.com',
    measurementId: 'G-HVVD185MLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsdrR0yB_s6uLrE6MdPJaMmtSWKZmCQh4',
    appId: '1:648139194030:android:c2e150efff3cfd2cee773f',
    messagingSenderId: '648139194030',
    projectId: 'project-matkul',
    storageBucket: 'project-matkul.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDruZXbUl3zF3NGXdKnPnd0vxY_KsmHqlk',
    appId: '1:648139194030:ios:dd5c28aa0e782b33ee773f',
    messagingSenderId: '648139194030',
    projectId: 'project-matkul',
    storageBucket: 'project-matkul.appspot.com',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDruZXbUl3zF3NGXdKnPnd0vxY_KsmHqlk',
    appId: '1:648139194030:ios:dd5c28aa0e782b33ee773f',
    messagingSenderId: '648139194030',
    projectId: 'project-matkul',
    storageBucket: 'project-matkul.appspot.com',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxhyr556e5rXAgtvJPZRibq0sNrLqdE40',
    appId: '1:648139194030:web:d683a13e2f78a9c2ee773f',
    messagingSenderId: '648139194030',
    projectId: 'project-matkul',
    authDomain: 'project-matkul.firebaseapp.com',
    storageBucket: 'project-matkul.appspot.com',
    measurementId: 'G-YX816HHEW7',
  );
}
